// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlt7bL74qUt90Jx9zOvzhDZFlgsH9kq-A',
    appId: '1:550835966627:web:a18074d3227ffbc9f0e516',
    messagingSenderId: '550835966627',
    projectId: 'riverpod-auth-ma22',
    authDomain: 'riverpod-auth-ma22.firebaseapp.com',
    storageBucket: 'riverpod-auth-ma22.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1wqWOIci1zoAMyRkYjSitUhHN1S8xZgY',
    appId: '1:550835966627:android:89a9974816724eeaf0e516',
    messagingSenderId: '550835966627',
    projectId: 'riverpod-auth-ma22',
    storageBucket: 'riverpod-auth-ma22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5lqXcqAnV1HhHUpDymCzsnIBsVavRHKo',
    appId: '1:550835966627:ios:093b23ed60e2b936f0e516',
    messagingSenderId: '550835966627',
    projectId: 'riverpod-auth-ma22',
    storageBucket: 'riverpod-auth-ma22.appspot.com',
    iosClientId: '550835966627-ffkn06llivk2rflm2bg9gmp8u634pc60.apps.googleusercontent.com',
    iosBundleId: 'no.ntnu.exerciseE5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5lqXcqAnV1HhHUpDymCzsnIBsVavRHKo',
    appId: '1:550835966627:ios:093b23ed60e2b936f0e516',
    messagingSenderId: '550835966627',
    projectId: 'riverpod-auth-ma22',
    storageBucket: 'riverpod-auth-ma22.appspot.com',
    iosClientId: '550835966627-ffkn06llivk2rflm2bg9gmp8u634pc60.apps.googleusercontent.com',
    iosBundleId: 'no.ntnu.exerciseE5',
  );
}
