name: riverpod_list_example
description: Example for using StateNotifierProvider from the RiverPod library
version: 1.0.0

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: 2.0.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
